import { Chord } from '../types';

export const chords: Chord[] = [
  // ============================================
  // MAJOR CHORDS (12 keys)
  // ============================================
  {
    id: 'c-major',
    primaryName: 'C',
    alternateNames: ['Cmaj', 'CM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G'],
    diagram: {
      strings: [-1, 3, 2, 0, 1, 0],
      fingers: [0, 3, 2, 0, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'csharp-major',
    primaryName: 'C#',
    alternateNames: ['C#maj', 'C#M', 'Db', 'Dbmaj'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['C#', 'E#', 'G#'],
    diagram: {
      strings: [-1, 4, 3, 1, 2, 1],
      fingers: [0, 4, 3, 1, 2, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'd-major',
    primaryName: 'D',
    alternateNames: ['Dmaj', 'DM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 2],
      fingers: [0, 0, 0, 1, 3, 2],
      baseFret: 0,
    },
  },
  {
    id: 'dsharp-major',
    primaryName: 'D#',
    alternateNames: ['D#maj', 'D#M', 'Eb', 'Ebmaj'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['D#', 'G', 'A#'],
    diagram: {
      strings: [-1, 6, 5, 3, 4, 3],
      fingers: [0, 4, 3, 1, 2, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'e-major',
    primaryName: 'E',
    alternateNames: ['Emaj', 'EM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B'],
    diagram: {
      strings: [0, 2, 2, 1, 0, 0],
      fingers: [0, 2, 3, 1, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'f-major',
    primaryName: 'F',
    alternateNames: ['Fmaj', 'FM'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['F', 'A', 'C'],
    diagram: {
      strings: [1, 1, 2, 3, 3, 1],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'fsharp-major',
    primaryName: 'F#',
    alternateNames: ['F#maj', 'F#M', 'Gb', 'Gbmaj'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['F#', 'A#', 'C#'],
    diagram: {
      strings: [2, 2, 3, 4, 4, 2],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  {
    id: 'g-major',
    primaryName: 'G',
    alternateNames: ['Gmaj', 'GM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 3],
      fingers: [2, 1, 0, 0, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'gsharp-major',
    primaryName: 'G#',
    alternateNames: ['G#maj', 'G#M', 'Ab', 'Abmaj'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['G#', 'C', 'D#'],
    diagram: {
      strings: [4, 4, 6, 6, 6, 4],
      fingers: [1, 1, 3, 3, 3, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'a-major',
    primaryName: 'A',
    alternateNames: ['Amaj', 'AM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 2, 0],
      fingers: [0, 0, 1, 2, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'asharp-major',
    primaryName: 'A#',
    alternateNames: ['A#maj', 'A#M', 'Bb', 'Bbmaj'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['A#', 'D', 'F'],
    diagram: {
      strings: [1, 1, 3, 3, 3, 1],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'b-major',
    primaryName: 'B',
    alternateNames: ['Bmaj', 'BM'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['B', 'D#', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, 4, 2],
      fingers: [0, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },

  // ============================================
  // MINOR CHORDS (12 keys)
  // ============================================
  {
    id: 'c-minor',
    primaryName: 'Cm',
    alternateNames: ['Cmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['C', 'Eb', 'G'],
    diagram: {
      strings: [-1, 3, 5, 5, 4, 3],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'csharp-minor',
    primaryName: 'C#m',
    alternateNames: ['C#min', 'Dbm', 'Dbmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['C#', 'E', 'G#'],
    diagram: {
      strings: [-1, 4, 6, 6, 5, 4],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'd-minor',
    primaryName: 'Dm',
    alternateNames: ['Dmin'],
    type: 'minor',
    difficulty: 'beginner',
    notes: ['D', 'F', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 1],
      fingers: [0, 0, 0, 2, 3, 1],
      baseFret: 0,
    },
  },
  {
    id: 'dsharp-minor',
    primaryName: 'D#m',
    alternateNames: ['D#min', 'Ebm', 'Ebmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['D#', 'F#', 'A#'],
    diagram: {
      strings: [-1, 6, 8, 8, 7, 6],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [6],
    },
  },
  {
    id: 'e-minor',
    primaryName: 'Em',
    alternateNames: ['Emin'],
    type: 'minor',
    difficulty: 'beginner',
    notes: ['E', 'G', 'B'],
    diagram: {
      strings: [0, 2, 2, 0, 0, 0],
      fingers: [0, 2, 3, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'f-minor',
    primaryName: 'Fm',
    alternateNames: ['Fmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['F', 'Ab', 'C'],
    diagram: {
      strings: [1, 1, 1, 3, 3, 1],
      fingers: [1, 1, 1, 3, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'fsharp-minor',
    primaryName: 'F#m',
    alternateNames: ['F#min', 'Gbm', 'Gbmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['F#', 'A', 'C#'],
    diagram: {
      strings: [2, 2, 2, 4, 4, 2],
      fingers: [1, 1, 1, 3, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  {
    id: 'g-minor',
    primaryName: 'Gm',
    alternateNames: ['Gmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['G', 'Bb', 'D'],
    diagram: {
      strings: [3, 3, 5, 5, 3, 3],
      fingers: [1, 1, 3, 4, 1, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'gsharp-minor',
    primaryName: 'G#m',
    alternateNames: ['G#min', 'Abm', 'Abmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['G#', 'B', 'D#'],
    diagram: {
      strings: [4, 4, 6, 6, 5, 4],
      fingers: [1, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'a-minor',
    primaryName: 'Am',
    alternateNames: ['Amin'],
    type: 'minor',
    difficulty: 'beginner',
    notes: ['A', 'C', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 1, 0],
      fingers: [0, 0, 2, 3, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'asharp-minor',
    primaryName: 'A#m',
    alternateNames: ['A#min', 'Bbm', 'Bbmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['A#', 'C#', 'F'],
    diagram: {
      strings: [1, 1, 3, 3, 2, 1],
      fingers: [1, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'b-minor',
    primaryName: 'Bm',
    alternateNames: ['Bmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['B', 'D', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, 3, 2],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [2],
    },
  },

  // ============================================
  // DOMINANT 7TH CHORDS (12 keys)
  // ============================================
  {
    id: 'c7',
    primaryName: 'C7',
    alternateNames: ['Cdom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G', 'Bb'],
    diagram: {
      strings: [-1, 3, 2, 3, 1, 0],
      fingers: [0, 3, 2, 4, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'csharp7',
    primaryName: 'C#7',
    alternateNames: ['C#dom7', 'Db7', 'Dbdom7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['C#', 'E#', 'G#', 'B'],
    diagram: {
      strings: [-1, 4, 3, 4, 2, -1],
      fingers: [0, 3, 2, 4, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd7',
    primaryName: 'D7',
    alternateNames: ['Ddom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'C'],
    diagram: {
      strings: [-1, -1, 0, 2, 1, 2],
      fingers: [0, 0, 0, 2, 1, 3],
      baseFret: 0,
    },
  },
  {
    id: 'dsharp7',
    primaryName: 'D#7',
    alternateNames: ['D#dom7', 'Eb7', 'Ebdom7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['D#', 'G', 'A#', 'C#'],
    diagram: {
      strings: [-1, 6, 5, 6, 4, -1],
      fingers: [0, 3, 2, 4, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'e7',
    primaryName: 'E7',
    alternateNames: ['Edom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'D'],
    diagram: {
      strings: [0, 2, 0, 1, 0, 0],
      fingers: [0, 2, 0, 1, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'f7',
    primaryName: 'F7',
    alternateNames: ['Fdom7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['F', 'A', 'C', 'Eb'],
    diagram: {
      strings: [1, 1, 2, 1, 3, 1],
      fingers: [1, 1, 2, 1, 3, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'fsharp7',
    primaryName: 'F#7',
    alternateNames: ['F#dom7', 'Gb7', 'Gbdom7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['F#', 'A#', 'C#', 'E'],
    diagram: {
      strings: [2, 2, 3, 2, 4, 2],
      fingers: [1, 1, 2, 1, 3, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  {
    id: 'g7',
    primaryName: 'G7',
    alternateNames: ['Gdom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'F'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 1],
      fingers: [3, 2, 0, 0, 0, 1],
      baseFret: 0,
    },
  },
  {
    id: 'gsharp7',
    primaryName: 'G#7',
    alternateNames: ['G#dom7', 'Ab7', 'Abdom7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['G#', 'C', 'D#', 'F#'],
    diagram: {
      strings: [4, 4, 5, 4, 6, 4],
      fingers: [1, 1, 2, 1, 3, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'a7',
    primaryName: 'A7',
    alternateNames: ['Adom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'G'],
    diagram: {
      strings: [-1, 0, 2, 0, 2, 0],
      fingers: [0, 0, 1, 0, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'asharp7',
    primaryName: 'A#7',
    alternateNames: ['A#dom7', 'Bb7', 'Bbdom7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['A#', 'D', 'F', 'G#'],
    diagram: {
      strings: [1, 1, 3, 1, 3, 1],
      fingers: [1, 1, 2, 1, 3, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'b7',
    primaryName: 'B7',
    alternateNames: ['Bdom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['B', 'D#', 'F#', 'A'],
    diagram: {
      strings: [-1, 2, 1, 2, 0, 2],
      fingers: [0, 2, 1, 3, 0, 4],
      baseFret: 0,
    },
  },

  // ============================================
  // MAJOR 7TH CHORDS (12 keys)
  // ============================================
  {
    id: 'cmaj7',
    primaryName: 'Cmaj7',
    alternateNames: ['CM7', 'C major 7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G', 'B'],
    diagram: {
      strings: [-1, 3, 2, 0, 0, 0],
      fingers: [0, 3, 2, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'csharpmaj7',
    primaryName: 'C#maj7',
    alternateNames: ['C#M7', 'Dbmaj7', 'DbM7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['C#', 'E#', 'G#', 'B#'],
    diagram: {
      strings: [-1, 4, 3, 1, 1, 1],
      fingers: [0, 4, 3, 1, 1, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'dmaj7',
    primaryName: 'Dmaj7',
    alternateNames: ['DM7', 'D major 7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'C#'],
    diagram: {
      strings: [-1, -1, 0, 2, 2, 2],
      fingers: [0, 0, 0, 1, 1, 1],
      baseFret: 0,
    },
  },
  {
    id: 'dsharpmaj7',
    primaryName: 'D#maj7',
    alternateNames: ['D#M7', 'Ebmaj7', 'EbM7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['D#', 'G', 'A#', 'D'],
    diagram: {
      strings: [-1, 6, 5, 3, 3, 3],
      fingers: [0, 4, 3, 1, 1, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'emaj7',
    primaryName: 'Emaj7',
    alternateNames: ['EM7', 'E major 7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'D#'],
    diagram: {
      strings: [0, 2, 1, 1, 0, 0],
      fingers: [0, 3, 1, 2, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'fmaj7',
    primaryName: 'Fmaj7',
    alternateNames: ['FM7', 'F major 7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['F', 'A', 'C', 'E'],
    diagram: {
      strings: [-1, -1, 3, 2, 1, 0],
      fingers: [0, 0, 3, 2, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'fsharpmaj7',
    primaryName: 'F#maj7',
    alternateNames: ['F#M7', 'Gbmaj7', 'GbM7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['F#', 'A#', 'C#', 'E#'],
    diagram: {
      strings: [2, 2, 3, 3, 4, 2],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  {
    id: 'gmaj7',
    primaryName: 'Gmaj7',
    alternateNames: ['GM7', 'G major 7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'F#'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 2],
      fingers: [2, 1, 0, 0, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'gsharpmaj7',
    primaryName: 'G#maj7',
    alternateNames: ['G#M7', 'Abmaj7', 'AbM7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['G#', 'C', 'D#', 'G'],
    diagram: {
      strings: [4, 4, 5, 5, 6, 4],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'amaj7',
    primaryName: 'Amaj7',
    alternateNames: ['AM7', 'A major 7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'G#'],
    diagram: {
      strings: [-1, 0, 2, 1, 2, 0],
      fingers: [0, 0, 2, 1, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'asharpmaj7',
    primaryName: 'A#maj7',
    alternateNames: ['A#M7', 'Bbmaj7', 'BbM7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['A#', 'D', 'F', 'A'],
    diagram: {
      strings: [1, 1, 3, 2, 3, 1],
      fingers: [1, 1, 3, 2, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'bmaj7',
    primaryName: 'Bmaj7',
    alternateNames: ['BM7', 'B major 7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['B', 'D#', 'F#', 'A#'],
    diagram: {
      strings: [-1, 2, 4, 3, 4, 2],
      fingers: [0, 1, 3, 2, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },

  // ============================================
  // MINOR 7TH CHORDS (12 keys)
  // ============================================
  {
    id: 'cm7',
    primaryName: 'Cm7',
    alternateNames: ['Cmin7', 'C-7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['C', 'Eb', 'G', 'Bb'],
    diagram: {
      strings: [-1, 3, 5, 3, 4, 3],
      fingers: [0, 1, 3, 1, 2, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'csharpm7',
    primaryName: 'C#m7',
    alternateNames: ['C#min7', 'Dbm7', 'Dbmin7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['C#', 'E', 'G#', 'B'],
    diagram: {
      strings: [-1, 4, 6, 4, 5, 4],
      fingers: [0, 1, 3, 1, 2, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'dm7',
    primaryName: 'Dm7',
    alternateNames: ['Dmin7', 'D-7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['D', 'F', 'A', 'C'],
    diagram: {
      strings: [-1, -1, 0, 2, 1, 1],
      fingers: [0, 0, 0, 2, 1, 1],
      baseFret: 0,
    },
  },
  {
    id: 'dsharpm7',
    primaryName: 'D#m7',
    alternateNames: ['D#min7', 'Ebm7', 'Ebmin7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['D#', 'F#', 'A#', 'C#'],
    diagram: {
      strings: [-1, 6, 8, 6, 7, 6],
      fingers: [0, 1, 3, 1, 2, 1],
      baseFret: 0,
      barres: [6],
    },
  },
  {
    id: 'em7',
    primaryName: 'Em7',
    alternateNames: ['Emin7', 'E-7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['E', 'G', 'B', 'D'],
    diagram: {
      strings: [0, 2, 0, 0, 0, 0],
      fingers: [0, 1, 0, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'fm7',
    primaryName: 'Fm7',
    alternateNames: ['Fmin7', 'F-7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['F', 'Ab', 'C', 'Eb'],
    diagram: {
      strings: [1, 1, 1, 1, 1, 1],
      fingers: [1, 1, 1, 1, 1, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'fsharpm7',
    primaryName: 'F#m7',
    alternateNames: ['F#min7', 'Gbm7', 'Gbmin7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['F#', 'A', 'C#', 'E'],
    diagram: {
      strings: [2, 2, 2, 2, 2, 2],
      fingers: [1, 1, 1, 1, 1, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  {
    id: 'gm7',
    primaryName: 'Gm7',
    alternateNames: ['Gmin7', 'G-7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['G', 'Bb', 'D', 'F'],
    diagram: {
      strings: [3, 3, 3, 3, 3, 3],
      fingers: [1, 1, 1, 1, 1, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'gsharpm7',
    primaryName: 'G#m7',
    alternateNames: ['G#min7', 'Abm7', 'Abmin7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['G#', 'B', 'D#', 'F#'],
    diagram: {
      strings: [4, 4, 4, 4, 4, 4],
      fingers: [1, 1, 1, 1, 1, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'am7',
    primaryName: 'Am7',
    alternateNames: ['Amin7', 'A-7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['A', 'C', 'E', 'G'],
    diagram: {
      strings: [-1, 0, 2, 0, 1, 0],
      fingers: [0, 0, 2, 0, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'asharpm7',
    primaryName: 'A#m7',
    alternateNames: ['A#min7', 'Bbm7', 'Bbmin7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['A#', 'C#', 'F', 'G#'],
    diagram: {
      strings: [1, 1, 1, 1, 2, 1],
      fingers: [1, 1, 1, 1, 2, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'bm7',
    primaryName: 'Bm7',
    alternateNames: ['Bmin7', 'B-7'],
    type: '7th',
    difficulty: 'intermediate',
    notes: ['B', 'D', 'F#', 'A'],
    diagram: {
      strings: [-1, 2, 4, 2, 3, 2],
      fingers: [0, 1, 3, 1, 2, 1],
      baseFret: 0,
      barres: [2],
    },
  },

  // ============================================
  // SUS2 CHORDS (6 common)
  // ============================================
  {
    id: 'csus2',
    primaryName: 'Csus2',
    alternateNames: ['C2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['C', 'D', 'G'],
    diagram: {
      strings: [-1, 3, 0, 0, 1, 3],
      fingers: [0, 2, 0, 0, 1, 3],
      baseFret: 0,
    },
  },
  {
    id: 'dsus2',
    primaryName: 'Dsus2',
    alternateNames: ['D2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['D', 'E', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 0],
      fingers: [0, 0, 0, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'esus2',
    primaryName: 'Esus2',
    alternateNames: ['E2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['E', 'F#', 'B'],
    diagram: {
      strings: [0, 2, 4, 4, 0, 0],
      fingers: [0, 1, 3, 4, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gsus2',
    primaryName: 'Gsus2',
    alternateNames: ['G2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['G', 'A', 'D'],
    diagram: {
      strings: [3, 0, 0, 0, 3, 3],
      fingers: [1, 0, 0, 0, 3, 4],
      baseFret: 0,
    },
  },
  {
    id: 'asus2',
    primaryName: 'Asus2',
    alternateNames: ['A2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['A', 'B', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 0, 0],
      fingers: [0, 0, 1, 2, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'bsus2',
    primaryName: 'Bsus2',
    alternateNames: ['B2'],
    type: 'sus',
    difficulty: 'intermediate',
    notes: ['B', 'C#', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, 2, 2],
      fingers: [0, 1, 3, 4, 1, 1],
      baseFret: 0,
      barres: [2],
    },
  },

  // ============================================
  // SUS4 CHORDS (6 common)
  // ============================================
  {
    id: 'csus4',
    primaryName: 'Csus4',
    alternateNames: ['C4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['C', 'F', 'G'],
    diagram: {
      strings: [-1, 3, 3, 0, 1, 1],
      fingers: [0, 2, 3, 0, 1, 1],
      baseFret: 0,
    },
  },
  {
    id: 'dsus4',
    primaryName: 'Dsus4',
    alternateNames: ['D4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['D', 'G', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 3],
      fingers: [0, 0, 0, 1, 2, 3],
      baseFret: 0,
    },
  },
  {
    id: 'esus4',
    primaryName: 'Esus4',
    alternateNames: ['E4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['E', 'A', 'B'],
    diagram: {
      strings: [0, 2, 2, 2, 0, 0],
      fingers: [0, 2, 3, 4, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gsus4',
    primaryName: 'Gsus4',
    alternateNames: ['G4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['G', 'C', 'D'],
    diagram: {
      strings: [3, 3, 0, 0, 1, 3],
      fingers: [2, 3, 0, 0, 1, 4],
      baseFret: 0,
    },
  },
  {
    id: 'asus4',
    primaryName: 'Asus4',
    alternateNames: ['A4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['A', 'D', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 3, 0],
      fingers: [0, 0, 1, 2, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'bsus4',
    primaryName: 'Bsus4',
    alternateNames: ['B4'],
    type: 'sus',
    difficulty: 'intermediate',
    notes: ['B', 'E', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, 5, 2],
      fingers: [0, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },

  // ============================================
  // POWER CHORDS (6 common)
  // ============================================
  {
    id: 'c5',
    primaryName: 'C5',
    alternateNames: ['C power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['C', 'G'],
    diagram: {
      strings: [-1, 3, 5, 5, -1, -1],
      fingers: [0, 1, 3, 4, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd5',
    primaryName: 'D5',
    alternateNames: ['D power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['D', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, -1],
      fingers: [0, 0, 0, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'e5',
    primaryName: 'E5',
    alternateNames: ['E power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['E', 'B'],
    diagram: {
      strings: [0, 2, 2, -1, -1, -1],
      fingers: [0, 1, 2, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'f5',
    primaryName: 'F5',
    alternateNames: ['F power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['F', 'C'],
    diagram: {
      strings: [1, 3, 3, -1, -1, -1],
      fingers: [1, 3, 4, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'g5',
    primaryName: 'G5',
    alternateNames: ['G power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['G', 'D'],
    diagram: {
      strings: [3, 5, 5, -1, -1, -1],
      fingers: [1, 3, 4, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'a5',
    primaryName: 'A5',
    alternateNames: ['A power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['A', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, -1, -1],
      fingers: [0, 0, 1, 2, 0, 0],
      baseFret: 0,
    },
  },

  // ============================================
  // DIMINISHED CHORDS (4 common)
  // ============================================
  {
    id: 'cdim',
    primaryName: 'Cdim',
    alternateNames: ['Co', 'Cdim7'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['C', 'Eb', 'Gb'],
    diagram: {
      strings: [-1, 3, 4, 2, 4, -1],
      fingers: [0, 2, 3, 1, 4, 0],
      baseFret: 0,
    },
  },
  {
    id: 'ddim',
    primaryName: 'Ddim',
    alternateNames: ['Do'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['D', 'F', 'Ab'],
    diagram: {
      strings: [-1, -1, 0, 1, 3, 1],
      fingers: [0, 0, 0, 1, 3, 2],
      baseFret: 0,
    },
  },
  {
    id: 'edim',
    primaryName: 'Edim',
    alternateNames: ['Eo'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['E', 'G', 'Bb'],
    diagram: {
      strings: [0, 1, 2, 0, -1, -1],
      fingers: [0, 1, 2, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'bdim',
    primaryName: 'Bdim',
    alternateNames: ['Bo'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['B', 'D', 'F'],
    diagram: {
      strings: [-1, 2, 3, 4, 3, -1],
      fingers: [0, 1, 2, 4, 3, 0],
      baseFret: 0,
    },
  },

  // ============================================
  // AUGMENTED CHORDS (4 common)
  // ============================================
  {
    id: 'caug',
    primaryName: 'Caug',
    alternateNames: ['C+', 'C+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['C', 'E', 'G#'],
    diagram: {
      strings: [-1, 3, 2, 1, 1, 0],
      fingers: [0, 4, 3, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'daug',
    primaryName: 'Daug',
    alternateNames: ['D+', 'D+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['D', 'F#', 'A#'],
    diagram: {
      strings: [-1, -1, 0, 3, 3, 2],
      fingers: [0, 0, 0, 2, 3, 1],
      baseFret: 0,
    },
  },
  {
    id: 'eaug',
    primaryName: 'Eaug',
    alternateNames: ['E+', 'E+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['E', 'G#', 'C'],
    diagram: {
      strings: [0, 3, 2, 1, 1, 0],
      fingers: [0, 4, 3, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gaug',
    primaryName: 'Gaug',
    alternateNames: ['G+', 'G+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['G', 'B', 'D#'],
    diagram: {
      strings: [3, 2, 1, 0, 0, 3],
      fingers: [3, 2, 1, 0, 0, 4],
      baseFret: 0,
    },
  },

  // ============================================
  // ADD9 CHORDS (4 common)
  // ============================================
  {
    id: 'cadd9',
    primaryName: 'Cadd9',
    alternateNames: ['C(add9)', 'Cadd2'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G', 'D'],
    diagram: {
      strings: [-1, 3, 2, 0, 3, 0],
      fingers: [0, 2, 1, 0, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'dadd9',
    primaryName: 'Dadd9',
    alternateNames: ['D(add9)', 'Dadd2'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'E'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 0],
      fingers: [0, 0, 0, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gadd9',
    primaryName: 'Gadd9',
    alternateNames: ['G(add9)', 'Gadd2'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'A'],
    diagram: {
      strings: [3, 0, 0, 2, 0, 3],
      fingers: [2, 0, 0, 1, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'aadd9',
    primaryName: 'Aadd9',
    alternateNames: ['A(add9)', 'Aadd2'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'B'],
    diagram: {
      strings: [-1, 0, 2, 2, 0, 0],
      fingers: [0, 0, 1, 2, 0, 0],
      baseFret: 0,
    },
  },

  // ============================================
  // ADDITIONAL EXTENDED CHORDS (to reach 100+)
  // ============================================
  {
    id: 'a6',
    primaryName: 'A6',
    alternateNames: ['Amaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'F#'],
    diagram: {
      strings: [-1, 0, 2, 2, 2, 2],
      fingers: [0, 0, 1, 1, 1, 1],
      baseFret: 0,
    },
  },
  {
    id: 'c6',
    primaryName: 'C6',
    alternateNames: ['Cmaj6'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['C', 'E', 'G', 'A'],
    diagram: {
      strings: [-1, 3, 2, 2, 1, 0],
      fingers: [0, 4, 2, 3, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd6',
    primaryName: 'D6',
    alternateNames: ['Dmaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'B'],
    diagram: {
      strings: [-1, -1, 0, 2, 0, 2],
      fingers: [0, 0, 0, 1, 0, 2],
      baseFret: 0,
    },
  },
  {
    id: 'e6',
    primaryName: 'E6',
    alternateNames: ['Emaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'C#'],
    diagram: {
      strings: [0, 2, 2, 1, 2, 0],
      fingers: [0, 2, 3, 1, 4, 0],
      baseFret: 0,
    },
  },
  {
    id: 'g6',
    primaryName: 'G6',
    alternateNames: ['Gmaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'E'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 0],
      fingers: [2, 1, 0, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'am6',
    primaryName: 'Am6',
    alternateNames: ['Amin6'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['A', 'C', 'E', 'F#'],
    diagram: {
      strings: [-1, 0, 2, 2, 1, 2],
      fingers: [0, 0, 2, 3, 1, 4],
      baseFret: 0,
    },
  },
  {
    id: 'em6',
    primaryName: 'Em6',
    alternateNames: ['Emin6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['E', 'G', 'B', 'C#'],
    diagram: {
      strings: [0, 2, 2, 0, 2, 0],
      fingers: [0, 1, 2, 0, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'dm6',
    primaryName: 'Dm6',
    alternateNames: ['Dmin6'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['D', 'F', 'A', 'B'],
    diagram: {
      strings: [-1, -1, 0, 2, 0, 1],
      fingers: [0, 0, 0, 2, 0, 1],
      baseFret: 0,
    },
  },
  {
    id: 'c9',
    primaryName: 'C9',
    alternateNames: ['Cdom9'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['C', 'E', 'G', 'Bb', 'D'],
    diagram: {
      strings: [-1, 3, 2, 3, 3, 3],
      fingers: [0, 2, 1, 3, 3, 3],
      baseFret: 0,
    },
  },
  {
    id: 'd9',
    primaryName: 'D9',
    alternateNames: ['Ddom9'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['D', 'F#', 'A', 'C', 'E'],
    diagram: {
      strings: [-1, -1, 0, 2, 1, 0],
      fingers: [0, 0, 0, 2, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'e9',
    primaryName: 'E9',
    alternateNames: ['Edom9'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['E', 'G#', 'B', 'D', 'F#'],
    diagram: {
      strings: [0, 2, 0, 1, 0, 2],
      fingers: [0, 2, 0, 1, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'g9',
    primaryName: 'G9',
    alternateNames: ['Gdom9'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['G', 'B', 'D', 'F', 'A'],
    diagram: {
      strings: [3, 2, 0, 2, 0, 1],
      fingers: [3, 2, 0, 4, 0, 1],
      baseFret: 0,
    },
  },
  {
    id: 'a9',
    primaryName: 'A9',
    alternateNames: ['Adom9'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['A', 'C#', 'E', 'G', 'B'],
    diagram: {
      strings: [-1, 0, 2, 4, 2, 3],
      fingers: [0, 0, 1, 4, 2, 3],
      baseFret: 0,
    },
  },
  {
    id: 'b5',
    primaryName: 'B5',
    alternateNames: ['B power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['B', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, -1, -1],
      fingers: [0, 1, 3, 4, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'fsus2',
    primaryName: 'Fsus2',
    alternateNames: ['F2'],
    type: 'sus',
    difficulty: 'intermediate',
    notes: ['F', 'G', 'C'],
    diagram: {
      strings: [1, 1, 3, 3, 1, 1],
      fingers: [1, 1, 3, 4, 1, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'fsus4',
    primaryName: 'Fsus4',
    alternateNames: ['F4'],
    type: 'sus',
    difficulty: 'intermediate',
    notes: ['F', 'Bb', 'C'],
    diagram: {
      strings: [1, 1, 3, 3, 1, 1],
      fingers: [1, 1, 3, 4, 1, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'adim',
    primaryName: 'Adim',
    alternateNames: ['Ao'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['A', 'C', 'Eb'],
    diagram: {
      strings: [-1, 0, 1, 2, 1, -1],
      fingers: [0, 0, 1, 3, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gdim',
    primaryName: 'Gdim',
    alternateNames: ['Go'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['G', 'Bb', 'Db'],
    diagram: {
      strings: [3, 4, 5, 3, -1, -1],
      fingers: [1, 2, 3, 1, 0, 0],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'aaug',
    primaryName: 'Aaug',
    alternateNames: ['A+', 'A+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['A', 'C#', 'E#'],
    diagram: {
      strings: [-1, 0, 3, 2, 2, 1],
      fingers: [0, 0, 4, 2, 3, 1],
      baseFret: 0,
    },
  },
  {
    id: 'baug',
    primaryName: 'Baug',
    alternateNames: ['B+', 'B+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['B', 'D#', 'G'],
    diagram: {
      strings: [-1, 2, 1, 0, 0, -1],
      fingers: [0, 2, 1, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'faug',
    primaryName: 'Faug',
    alternateNames: ['F+', 'F+5'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['F', 'A', 'C#'],
    diagram: {
      strings: [1, 0, 3, 2, 2, 1],
      fingers: [1, 0, 4, 2, 3, 1],
      baseFret: 0,
    },
  },
  {
    id: 'eadd9',
    primaryName: 'Eadd9',
    alternateNames: ['E(add9)', 'Eadd2'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'F#'],
    diagram: {
      strings: [0, 2, 2, 1, 0, 2],
      fingers: [0, 2, 3, 1, 0, 4],
      baseFret: 0,
    },
  },
  {
    id: 'fadd9',
    primaryName: 'Fadd9',
    alternateNames: ['F(add9)', 'Fadd2'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['F', 'A', 'C', 'G'],
    diagram: {
      strings: [1, 0, 3, 0, 1, 1],
      fingers: [1, 0, 3, 0, 2, 1],
      baseFret: 0,
    },
  },
];

// Helper function to find chord by name
export function findChordByName(name: string): Chord | undefined {
  const normalizedName = name.toLowerCase().trim();
  return chords.find(
    (chord) =>
      chord.primaryName.toLowerCase() === normalizedName ||
      chord.alternateNames.some((alt) => alt.toLowerCase() === normalizedName)
  );
}

// Helper function to get chords by type
export function getChordsByType(type: Chord['type']): Chord[] {
  return chords.filter((chord) => chord.type === type);
}

// Helper function to get chords by difficulty
export function getChordsByDifficulty(difficulty: Chord['difficulty']): Chord[] {
  return chords.filter((chord) => chord.difficulty === difficulty);
}
