import { Chord } from '../types';

export const chords: Chord[] = [
  // Major chords
  {
    id: 'c-major',
    primaryName: 'C',
    alternateNames: ['Cmaj', 'CM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G'],
    diagram: {
      strings: [-1, 3, 2, 0, 1, 0],
      fingers: [0, 3, 2, 0, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd-major',
    primaryName: 'D',
    alternateNames: ['Dmaj', 'DM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 2],
      fingers: [0, 0, 0, 1, 3, 2],
      baseFret: 0,
    },
  },
  {
    id: 'e-major',
    primaryName: 'E',
    alternateNames: ['Emaj', 'EM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B'],
    diagram: {
      strings: [0, 2, 2, 1, 0, 0],
      fingers: [0, 2, 3, 1, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'g-major',
    primaryName: 'G',
    alternateNames: ['Gmaj', 'GM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 3],
      fingers: [2, 1, 0, 0, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'a-major',
    primaryName: 'A',
    alternateNames: ['Amaj', 'AM'],
    type: 'major',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 2, 0],
      fingers: [0, 0, 1, 2, 3, 0],
      baseFret: 0,
    },
  },
  // Minor chords
  {
    id: 'a-minor',
    primaryName: 'Am',
    alternateNames: ['Amin'],
    type: 'minor',
    difficulty: 'beginner',
    notes: ['A', 'C', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 1, 0],
      fingers: [0, 0, 2, 3, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd-minor',
    primaryName: 'Dm',
    alternateNames: ['Dmin'],
    type: 'minor',
    difficulty: 'beginner',
    notes: ['D', 'F', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 1],
      fingers: [0, 0, 0, 2, 3, 1],
      baseFret: 0,
    },
  },
  {
    id: 'e-minor',
    primaryName: 'Em',
    alternateNames: ['Emin'],
    type: 'minor',
    difficulty: 'beginner',
    notes: ['E', 'G', 'B'],
    diagram: {
      strings: [0, 2, 2, 0, 0, 0],
      fingers: [0, 2, 3, 0, 0, 0],
      baseFret: 0,
    },
  },
  // 7th chords
  {
    id: 'a7',
    primaryName: 'A7',
    alternateNames: ['Adom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'G'],
    diagram: {
      strings: [-1, 0, 2, 0, 2, 0],
      fingers: [0, 0, 1, 0, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'e7',
    primaryName: 'E7',
    alternateNames: ['Edom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'D'],
    diagram: {
      strings: [0, 2, 0, 1, 0, 0],
      fingers: [0, 2, 0, 1, 0, 0],
      baseFret: 0,
    },
  },
  // More Major chords
  {
    id: 'f-major',
    primaryName: 'F',
    alternateNames: ['Fmaj', 'FM'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['F', 'A', 'C'],
    diagram: {
      strings: [1, 1, 2, 3, 3, 1],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'b-major',
    primaryName: 'B',
    alternateNames: ['Bmaj', 'BM'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['B', 'D#', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, 4, 2],
      fingers: [0, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  // More Minor chords
  {
    id: 'b-minor',
    primaryName: 'Bm',
    alternateNames: ['Bmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['B', 'D', 'F#'],
    diagram: {
      strings: [-1, 2, 4, 4, 3, 2],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [2],
    },
  },
  {
    id: 'f-minor',
    primaryName: 'Fm',
    alternateNames: ['Fmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['F', 'Ab', 'C'],
    diagram: {
      strings: [1, 1, 1, 3, 3, 1],
      fingers: [1, 1, 1, 3, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'c-minor',
    primaryName: 'Cm',
    alternateNames: ['Cmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['C', 'Eb', 'G'],
    diagram: {
      strings: [-1, 3, 5, 5, 4, 3],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  {
    id: 'g-minor',
    primaryName: 'Gm',
    alternateNames: ['Gmin'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['G', 'Bb', 'D'],
    diagram: {
      strings: [3, 3, 5, 5, 3, 3],
      fingers: [1, 1, 3, 4, 1, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  // 7th chords
  {
    id: 'd7',
    primaryName: 'D7',
    alternateNames: ['Ddom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'C'],
    diagram: {
      strings: [-1, -1, 0, 2, 1, 2],
      fingers: [0, 0, 0, 2, 1, 3],
      baseFret: 0,
    },
  },
  {
    id: 'g7',
    primaryName: 'G7',
    alternateNames: ['Gdom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'F'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 1],
      fingers: [3, 2, 0, 0, 0, 1],
      baseFret: 0,
    },
  },
  {
    id: 'c7',
    primaryName: 'C7',
    alternateNames: ['Cdom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G', 'Bb'],
    diagram: {
      strings: [-1, 3, 2, 3, 1, 0],
      fingers: [0, 3, 2, 4, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'b7',
    primaryName: 'B7',
    alternateNames: ['Bdom7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['B', 'D#', 'F#', 'A'],
    diagram: {
      strings: [-1, 2, 1, 2, 0, 2],
      fingers: [0, 2, 1, 3, 0, 4],
      baseFret: 0,
    },
  },
  // Minor 7th chords
  {
    id: 'am7',
    primaryName: 'Am7',
    alternateNames: ['Amin7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['A', 'C', 'E', 'G'],
    diagram: {
      strings: [-1, 0, 2, 0, 1, 0],
      fingers: [0, 0, 2, 0, 1, 0],
      baseFret: 0,
    },
  },
  {
    id: 'em7',
    primaryName: 'Em7',
    alternateNames: ['Emin7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['E', 'G', 'B', 'D'],
    diagram: {
      strings: [0, 2, 0, 0, 0, 0],
      fingers: [0, 1, 0, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'dm7',
    primaryName: 'Dm7',
    alternateNames: ['Dmin7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['D', 'F', 'A', 'C'],
    diagram: {
      strings: [-1, -1, 0, 2, 1, 1],
      fingers: [0, 0, 0, 2, 1, 1],
      baseFret: 0,
    },
  },
  // Sus chords
  {
    id: 'dsus2',
    primaryName: 'Dsus2',
    alternateNames: ['D2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['D', 'E', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 0],
      fingers: [0, 0, 0, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'dsus4',
    primaryName: 'Dsus4',
    alternateNames: ['D4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['D', 'G', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 3],
      fingers: [0, 0, 0, 1, 2, 3],
      baseFret: 0,
    },
  },
  {
    id: 'asus2',
    primaryName: 'Asus2',
    alternateNames: ['A2'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['A', 'B', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 0, 0],
      fingers: [0, 0, 1, 2, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'asus4',
    primaryName: 'Asus4',
    alternateNames: ['A4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['A', 'D', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, 3, 0],
      fingers: [0, 0, 1, 2, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'esus4',
    primaryName: 'Esus4',
    alternateNames: ['E4'],
    type: 'sus',
    difficulty: 'beginner',
    notes: ['E', 'A', 'B'],
    diagram: {
      strings: [0, 2, 2, 2, 0, 0],
      fingers: [0, 2, 3, 4, 0, 0],
      baseFret: 0,
    },
  },
  // Major 7th chords
  {
    id: 'cmaj7',
    primaryName: 'Cmaj7',
    alternateNames: ['CM7', 'Cmaj7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G', 'B'],
    diagram: {
      strings: [-1, 3, 2, 0, 0, 0],
      fingers: [0, 3, 2, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gmaj7',
    primaryName: 'Gmaj7',
    alternateNames: ['GM7', 'Gmaj7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'F#'],
    diagram: {
      strings: [3, 2, 0, 0, 0, 2],
      fingers: [2, 1, 0, 0, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'dmaj7',
    primaryName: 'Dmaj7',
    alternateNames: ['DM7', 'Dmaj7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'C#'],
    diagram: {
      strings: [-1, -1, 0, 2, 2, 2],
      fingers: [0, 0, 0, 1, 1, 1],
      baseFret: 0,
    },
  },
  {
    id: 'amaj7',
    primaryName: 'Amaj7',
    alternateNames: ['AM7', 'Amaj7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'G#'],
    diagram: {
      strings: [-1, 0, 2, 1, 2, 0],
      fingers: [0, 0, 2, 1, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'emaj7',
    primaryName: 'Emaj7',
    alternateNames: ['EM7', 'Emaj7'],
    type: '7th',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'D#'],
    diagram: {
      strings: [0, 2, 1, 1, 0, 0],
      fingers: [0, 3, 1, 2, 0, 0],
      baseFret: 0,
    },
  },
  // Power chords
  {
    id: 'e5',
    primaryName: 'E5',
    alternateNames: ['E power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['E', 'B'],
    diagram: {
      strings: [0, 2, 2, -1, -1, -1],
      fingers: [0, 1, 2, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'a5',
    primaryName: 'A5',
    alternateNames: ['A power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['A', 'E'],
    diagram: {
      strings: [-1, 0, 2, 2, -1, -1],
      fingers: [0, 0, 1, 2, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd5',
    primaryName: 'D5',
    alternateNames: ['D power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['D', 'A'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, -1],
      fingers: [0, 0, 0, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'g5',
    primaryName: 'G5',
    alternateNames: ['G power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['G', 'D'],
    diagram: {
      strings: [3, 5, 5, -1, -1, -1],
      fingers: [1, 3, 4, 0, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'c5',
    primaryName: 'C5',
    alternateNames: ['C power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['C', 'G'],
    diagram: {
      strings: [-1, 3, 5, 5, -1, -1],
      fingers: [0, 1, 3, 4, 0, 0],
      baseFret: 0,
    },
  },
  {
    id: 'f5',
    primaryName: 'F5',
    alternateNames: ['F power'],
    type: 'power',
    difficulty: 'beginner',
    notes: ['F', 'C'],
    diagram: {
      strings: [1, 3, 3, -1, -1, -1],
      fingers: [1, 3, 4, 0, 0, 0],
      baseFret: 0,
    },
  },
  // Add9 chords
  {
    id: 'cadd9',
    primaryName: 'Cadd9',
    alternateNames: ['C(add9)'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['C', 'E', 'G', 'D'],
    diagram: {
      strings: [-1, 3, 2, 0, 3, 0],
      fingers: [0, 2, 1, 0, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'gadd9',
    primaryName: 'Gadd9',
    alternateNames: ['G(add9)'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['G', 'B', 'D', 'A'],
    diagram: {
      strings: [3, 0, 0, 2, 0, 3],
      fingers: [2, 0, 0, 1, 0, 3],
      baseFret: 0,
    },
  },
  {
    id: 'dadd9',
    primaryName: 'Dadd9',
    alternateNames: ['D(add9)'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'E'],
    diagram: {
      strings: [-1, -1, 0, 2, 3, 0],
      fingers: [0, 0, 0, 1, 2, 0],
      baseFret: 0,
    },
  },
  // Remaining major chords
  {
    id: 'ab-major',
    primaryName: 'Ab',
    alternateNames: ['Abmaj', 'G#'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['Ab', 'C', 'Eb'],
    diagram: {
      strings: [4, 4, 6, 6, 6, 4],
      fingers: [1, 1, 3, 3, 3, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'bb-major',
    primaryName: 'Bb',
    alternateNames: ['Bbmaj', 'A#'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['Bb', 'D', 'F'],
    diagram: {
      strings: [1, 1, 3, 3, 3, 1],
      fingers: [1, 1, 2, 3, 4, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'eb-major',
    primaryName: 'Eb',
    alternateNames: ['Ebmaj', 'D#'],
    type: 'major',
    difficulty: 'intermediate',
    notes: ['Eb', 'G', 'Bb'],
    diagram: {
      strings: [-1, 6, 5, 3, 4, 3],
      fingers: [0, 4, 3, 1, 2, 1],
      baseFret: 0,
      barres: [3],
    },
  },
  // Additional minor chords
  {
    id: 'ab-minor',
    primaryName: 'Abm',
    alternateNames: ['G#m'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['Ab', 'B', 'Eb'],
    diagram: {
      strings: [4, 4, 6, 6, 5, 4],
      fingers: [1, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [4],
    },
  },
  {
    id: 'bb-minor',
    primaryName: 'Bbm',
    alternateNames: ['A#m'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['Bb', 'Db', 'F'],
    diagram: {
      strings: [1, 1, 3, 3, 2, 1],
      fingers: [1, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [1],
    },
  },
  {
    id: 'eb-minor',
    primaryName: 'Ebm',
    alternateNames: ['D#m'],
    type: 'minor',
    difficulty: 'intermediate',
    notes: ['Eb', 'Gb', 'Bb'],
    diagram: {
      strings: [-1, 6, 8, 8, 7, 6],
      fingers: [0, 1, 3, 4, 2, 1],
      baseFret: 0,
      barres: [6],
    },
  },
  // Diminished chords
  {
    id: 'bdim',
    primaryName: 'Bdim',
    alternateNames: ['Bo'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['B', 'D', 'F'],
    diagram: {
      strings: [-1, 2, 3, 4, 3, -1],
      fingers: [0, 1, 2, 4, 3, 0],
      baseFret: 0,
    },
  },
  {
    id: 'cdim',
    primaryName: 'Cdim',
    alternateNames: ['Co'],
    type: 'dim',
    difficulty: 'intermediate',
    notes: ['C', 'Eb', 'Gb'],
    diagram: {
      strings: [-1, 3, 4, 2, 4, -1],
      fingers: [0, 2, 3, 1, 4, 0],
      baseFret: 0,
    },
  },
  // Augmented chords
  {
    id: 'caug',
    primaryName: 'Caug',
    alternateNames: ['C+'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['C', 'E', 'G#'],
    diagram: {
      strings: [-1, 3, 2, 1, 1, 0],
      fingers: [0, 4, 3, 1, 2, 0],
      baseFret: 0,
    },
  },
  {
    id: 'eaug',
    primaryName: 'Eaug',
    alternateNames: ['E+'],
    type: 'aug',
    difficulty: 'intermediate',
    notes: ['E', 'G#', 'C'],
    diagram: {
      strings: [0, 3, 2, 1, 1, 0],
      fingers: [0, 4, 3, 1, 2, 0],
      baseFret: 0,
    },
  },
  // 6th chords
  {
    id: 'a6',
    primaryName: 'A6',
    alternateNames: ['Amaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['A', 'C#', 'E', 'F#'],
    diagram: {
      strings: [-1, 0, 2, 2, 2, 2],
      fingers: [0, 0, 1, 1, 1, 1],
      baseFret: 0,
    },
  },
  {
    id: 'e6',
    primaryName: 'E6',
    alternateNames: ['Emaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['E', 'G#', 'B', 'C#'],
    diagram: {
      strings: [0, 2, 2, 1, 2, 0],
      fingers: [0, 2, 3, 1, 4, 0],
      baseFret: 0,
    },
  },
  {
    id: 'd6',
    primaryName: 'D6',
    alternateNames: ['Dmaj6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['D', 'F#', 'A', 'B'],
    diagram: {
      strings: [-1, -1, 0, 2, 0, 2],
      fingers: [0, 0, 0, 1, 0, 2],
      baseFret: 0,
    },
  },
  // Minor 6th
  {
    id: 'am6',
    primaryName: 'Am6',
    alternateNames: ['Amin6'],
    type: 'extended',
    difficulty: 'intermediate',
    notes: ['A', 'C', 'E', 'F#'],
    diagram: {
      strings: [-1, 0, 2, 2, 1, 2],
      fingers: [0, 0, 2, 3, 1, 4],
      baseFret: 0,
    },
  },
  {
    id: 'em6',
    primaryName: 'Em6',
    alternateNames: ['Emin6'],
    type: 'extended',
    difficulty: 'beginner',
    notes: ['E', 'G', 'B', 'C#'],
    diagram: {
      strings: [0, 2, 2, 0, 2, 0],
      fingers: [0, 1, 2, 0, 3, 0],
      baseFret: 0,
    },
  },
];

// Helper function to find chord by name
export function findChordByName(name: string): Chord | undefined {
  const normalizedName = name.toLowerCase().trim();
  return chords.find(
    (chord) =>
      chord.primaryName.toLowerCase() === normalizedName ||
      chord.alternateNames.some((alt) => alt.toLowerCase() === normalizedName)
  );
}

// Helper function to get chords by type
export function getChordsByType(type: Chord['type']): Chord[] {
  return chords.filter((chord) => chord.type === type);
}

// Helper function to get chords by difficulty
export function getChordsByDifficulty(difficulty: Chord['difficulty']): Chord[] {
  return chords.filter((chord) => chord.difficulty === difficulty);
}
