import { Song } from '../types';

export const songs: Song[] = [
  // 1. Greensleeves - Traditional English folk song (16th century)
  {
    id: 'greensleeves',
    title: 'Greensleeves',
    artist: 'Traditional',
    difficulty: 2,
    bpm: 90,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Simple chord changes with long holds',
        chart: [
          { id: 'gs-1-1', chord: 'Am', time: 0.0, duration: 2.0 },
          { id: 'gs-1-2', chord: 'G', time: 2.5, duration: 2.0 },
          { id: 'gs-1-3', chord: 'Am', time: 5.0, duration: 2.0 },
          { id: 'gs-1-4', chord: 'E', time: 7.5, duration: 2.0 },
          { id: 'gs-1-5', chord: 'Am', time: 10.0, duration: 2.0 },
          { id: 'gs-1-6', chord: 'G', time: 12.5, duration: 2.0 },
          { id: 'gs-1-7', chord: 'E', time: 15.0, duration: 2.0 },
          { id: 'gs-1-8', chord: 'Am', time: 17.5, duration: 2.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Intermediate',
        description: 'Faster tempo with full progression',
        chart: [
          { id: 'gs-2-1', chord: 'Am', time: 0.0, duration: 1.5 },
          { id: 'gs-2-2', chord: 'G', time: 1.8, duration: 1.5 },
          { id: 'gs-2-3', chord: 'Am', time: 3.6, duration: 1.5 },
          { id: 'gs-2-4', chord: 'E', time: 5.4, duration: 1.5 },
          { id: 'gs-2-5', chord: 'Am', time: 7.2, duration: 1.5 },
          { id: 'gs-2-6', chord: 'G', time: 9.0, duration: 1.5 },
          { id: 'gs-2-7', chord: 'E', time: 10.8, duration: 1.5 },
          { id: 'gs-2-8', chord: 'Am', time: 12.6, duration: 1.5 },
          { id: 'gs-2-9', chord: 'C', time: 14.4, duration: 1.5 },
          { id: 'gs-2-10', chord: 'G', time: 16.2, duration: 1.5 },
          { id: 'gs-2-11', chord: 'Am', time: 18.0, duration: 1.5 },
          { id: 'gs-2-12', chord: 'E', time: 19.8, duration: 1.5 },
        ],
      },
    ],
  },

  // 2. Amazing Grace - John Newton (1779)
  {
    id: 'amazing-grace',
    title: 'Amazing Grace',
    artist: 'John Newton',
    difficulty: 1,
    bpm: 70,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Classic hymn with simple chords',
        chart: [
          { id: 'ag-1-1', chord: 'G', time: 0.0, duration: 3.0 },
          { id: 'ag-1-2', chord: 'C', time: 3.5, duration: 3.0 },
          { id: 'ag-1-3', chord: 'G', time: 7.0, duration: 3.0 },
          { id: 'ag-1-4', chord: 'D', time: 10.5, duration: 3.0 },
          { id: 'ag-1-5', chord: 'G', time: 14.0, duration: 3.0 },
          { id: 'ag-1-6', chord: 'C', time: 17.5, duration: 3.0 },
          { id: 'ag-1-7', chord: 'G', time: 21.0, duration: 3.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Song',
        description: 'Complete arrangement with all verses',
        chart: [
          { id: 'ag-2-1', chord: 'G', time: 0.0, duration: 2.0 },
          { id: 'ag-2-2', chord: 'C', time: 2.5, duration: 2.0 },
          { id: 'ag-2-3', chord: 'G', time: 5.0, duration: 2.0 },
          { id: 'ag-2-4', chord: 'D', time: 7.5, duration: 2.0 },
          { id: 'ag-2-5', chord: 'G', time: 10.0, duration: 2.0 },
          { id: 'ag-2-6', chord: 'G7', time: 12.5, duration: 2.0 },
          { id: 'ag-2-7', chord: 'C', time: 15.0, duration: 2.0 },
          { id: 'ag-2-8', chord: 'G', time: 17.5, duration: 2.0 },
          { id: 'ag-2-9', chord: 'D', time: 20.0, duration: 2.0 },
          { id: 'ag-2-10', chord: 'G', time: 22.5, duration: 2.0 },
        ],
      },
    ],
  },

  // 3. Happy Birthday - Traditional (public domain since 2016)
  {
    id: 'happy-birthday',
    title: 'Happy Birthday',
    artist: 'Traditional',
    difficulty: 1,
    bpm: 100,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Simple party classic',
        chart: [
          { id: 'hb-1-1', chord: 'C', time: 0.0, duration: 2.0 },
          { id: 'hb-1-2', chord: 'G', time: 2.5, duration: 2.0 },
          { id: 'hb-1-3', chord: 'G', time: 5.0, duration: 2.0 },
          { id: 'hb-1-4', chord: 'C', time: 7.5, duration: 2.0 },
          { id: 'hb-1-5', chord: 'F', time: 10.0, duration: 2.0 },
          { id: 'hb-1-6', chord: 'C', time: 12.5, duration: 2.0 },
          { id: 'hb-1-7', chord: 'G', time: 15.0, duration: 2.0 },
          { id: 'hb-1-8', chord: 'C', time: 17.5, duration: 2.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Party Mode',
        description: 'Faster tempo for celebrations',
        chart: [
          { id: 'hb-2-1', chord: 'C', time: 0.0, duration: 1.0 },
          { id: 'hb-2-2', chord: 'C', time: 1.2, duration: 1.0 },
          { id: 'hb-2-3', chord: 'G', time: 2.4, duration: 1.0 },
          { id: 'hb-2-4', chord: 'G', time: 3.6, duration: 1.0 },
          { id: 'hb-2-5', chord: 'C', time: 4.8, duration: 1.0 },
          { id: 'hb-2-6', chord: 'F', time: 6.0, duration: 1.0 },
          { id: 'hb-2-7', chord: 'C', time: 7.2, duration: 1.0 },
          { id: 'hb-2-8', chord: 'G7', time: 8.4, duration: 1.0 },
          { id: 'hb-2-9', chord: 'C', time: 9.6, duration: 1.0 },
          { id: 'hb-2-10', chord: 'C', time: 10.8, duration: 1.0 },
        ],
      },
    ],
  },

  // 4. Auld Lang Syne - Robert Burns (1788)
  {
    id: 'auld-lang-syne',
    title: 'Auld Lang Syne',
    artist: 'Robert Burns',
    difficulty: 2,
    bpm: 80,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'New Year classic made easy',
        chart: [
          { id: 'als-1-1', chord: 'G', time: 0.0, duration: 2.5 },
          { id: 'als-1-2', chord: 'D', time: 3.0, duration: 2.5 },
          { id: 'als-1-3', chord: 'G', time: 6.0, duration: 2.5 },
          { id: 'als-1-4', chord: 'C', time: 9.0, duration: 2.5 },
          { id: 'als-1-5', chord: 'G', time: 12.0, duration: 2.5 },
          { id: 'als-1-6', chord: 'D', time: 15.0, duration: 2.5 },
          { id: 'als-1-7', chord: 'G', time: 18.0, duration: 2.5 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Arrangement',
        description: 'Complete song with chord variations',
        chart: [
          { id: 'als-2-1', chord: 'G', time: 0.0, duration: 1.5 },
          { id: 'als-2-2', chord: 'D', time: 2.0, duration: 1.5 },
          { id: 'als-2-3', chord: 'Em', time: 4.0, duration: 1.5 },
          { id: 'als-2-4', chord: 'G', time: 6.0, duration: 1.5 },
          { id: 'als-2-5', chord: 'C', time: 8.0, duration: 1.5 },
          { id: 'als-2-6', chord: 'G', time: 10.0, duration: 1.5 },
          { id: 'als-2-7', chord: 'D', time: 12.0, duration: 1.5 },
          { id: 'als-2-8', chord: 'G', time: 14.0, duration: 1.5 },
          { id: 'als-2-9', chord: 'C', time: 16.0, duration: 1.5 },
          { id: 'als-2-10', chord: 'Em', time: 18.0, duration: 1.5 },
          { id: 'als-2-11', chord: 'D', time: 20.0, duration: 1.5 },
          { id: 'als-2-12', chord: 'G', time: 22.0, duration: 1.5 },
        ],
      },
    ],
  },

  // 5. When The Saints Go Marching In - Traditional spiritual
  {
    id: 'when-the-saints',
    title: 'When The Saints Go Marching In',
    artist: 'Traditional',
    difficulty: 2,
    bpm: 110,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Classic spiritual with simple changes',
        chart: [
          { id: 'wts-1-1', chord: 'G', time: 0.0, duration: 2.0 },
          { id: 'wts-1-2', chord: 'G', time: 2.5, duration: 2.0 },
          { id: 'wts-1-3', chord: 'D', time: 5.0, duration: 2.0 },
          { id: 'wts-1-4', chord: 'G', time: 7.5, duration: 2.0 },
          { id: 'wts-1-5', chord: 'C', time: 10.0, duration: 2.0 },
          { id: 'wts-1-6', chord: 'G', time: 12.5, duration: 2.0 },
          { id: 'wts-1-7', chord: 'D', time: 15.0, duration: 2.0 },
          { id: 'wts-1-8', chord: 'G', time: 17.5, duration: 2.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'March Tempo',
        description: 'Full energy marching pace',
        chart: [
          { id: 'wts-2-1', chord: 'G', time: 0.0, duration: 1.0 },
          { id: 'wts-2-2', chord: 'G', time: 1.2, duration: 1.0 },
          { id: 'wts-2-3', chord: 'G', time: 2.4, duration: 1.0 },
          { id: 'wts-2-4', chord: 'D7', time: 3.6, duration: 1.0 },
          { id: 'wts-2-5', chord: 'G', time: 4.8, duration: 1.0 },
          { id: 'wts-2-6', chord: 'G7', time: 6.0, duration: 1.0 },
          { id: 'wts-2-7', chord: 'C', time: 7.2, duration: 1.0 },
          { id: 'wts-2-8', chord: 'G', time: 8.4, duration: 1.0 },
          { id: 'wts-2-9', chord: 'D', time: 9.6, duration: 1.0 },
          { id: 'wts-2-10', chord: 'G', time: 10.8, duration: 1.0 },
          { id: 'wts-2-11', chord: 'C', time: 12.0, duration: 1.0 },
          { id: 'wts-2-12', chord: 'G', time: 13.2, duration: 1.0 },
        ],
      },
    ],
  },

  // 6. Scarborough Fair - Traditional English ballad
  {
    id: 'scarborough-fair',
    title: 'Scarborough Fair',
    artist: 'Traditional',
    difficulty: 3,
    bpm: 85,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Medieval ballad with minor chords',
        chart: [
          { id: 'sf-1-1', chord: 'Am', time: 0.0, duration: 3.0 },
          { id: 'sf-1-2', chord: 'G', time: 3.5, duration: 3.0 },
          { id: 'sf-1-3', chord: 'Am', time: 7.0, duration: 3.0 },
          { id: 'sf-1-4', chord: 'C', time: 10.5, duration: 3.0 },
          { id: 'sf-1-5', chord: 'Am', time: 14.0, duration: 3.0 },
          { id: 'sf-1-6', chord: 'G', time: 17.5, duration: 3.0 },
          { id: 'sf-1-7', chord: 'Am', time: 21.0, duration: 3.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Ballad',
        description: 'Complete arrangement with embellishments',
        chart: [
          { id: 'sf-2-1', chord: 'Am', time: 0.0, duration: 2.0 },
          { id: 'sf-2-2', chord: 'G', time: 2.5, duration: 2.0 },
          { id: 'sf-2-3', chord: 'Am', time: 5.0, duration: 2.0 },
          { id: 'sf-2-4', chord: 'C', time: 7.5, duration: 2.0 },
          { id: 'sf-2-5', chord: 'Am', time: 10.0, duration: 2.0 },
          { id: 'sf-2-6', chord: 'D', time: 12.5, duration: 2.0 },
          { id: 'sf-2-7', chord: 'Am', time: 15.0, duration: 2.0 },
          { id: 'sf-2-8', chord: 'Em', time: 17.5, duration: 2.0 },
          { id: 'sf-2-9', chord: 'Am', time: 20.0, duration: 2.0 },
          { id: 'sf-2-10', chord: 'G', time: 22.5, duration: 2.0 },
          { id: 'sf-2-11', chord: 'C', time: 25.0, duration: 2.0 },
          { id: 'sf-2-12', chord: 'Am', time: 27.5, duration: 2.0 },
        ],
      },
    ],
  },

  // 7. House of the Rising Sun - Traditional American folk
  {
    id: 'house-rising-sun',
    title: 'House of the Rising Sun',
    artist: 'Traditional',
    difficulty: 3,
    bpm: 95,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Classic folk progression simplified',
        chart: [
          { id: 'hrs-1-1', chord: 'Am', time: 0.0, duration: 2.5 },
          { id: 'hrs-1-2', chord: 'C', time: 3.0, duration: 2.5 },
          { id: 'hrs-1-3', chord: 'D', time: 6.0, duration: 2.5 },
          { id: 'hrs-1-4', chord: 'F', time: 9.0, duration: 2.5 },
          { id: 'hrs-1-5', chord: 'Am', time: 12.0, duration: 2.5 },
          { id: 'hrs-1-6', chord: 'E', time: 15.0, duration: 2.5 },
          { id: 'hrs-1-7', chord: 'Am', time: 18.0, duration: 2.5 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Verse',
        description: 'Complete verse with arpeggiated feel',
        chart: [
          { id: 'hrs-2-1', chord: 'Am', time: 0.0, duration: 1.5 },
          { id: 'hrs-2-2', chord: 'C', time: 2.0, duration: 1.5 },
          { id: 'hrs-2-3', chord: 'D', time: 4.0, duration: 1.5 },
          { id: 'hrs-2-4', chord: 'F', time: 6.0, duration: 1.5 },
          { id: 'hrs-2-5', chord: 'Am', time: 8.0, duration: 1.5 },
          { id: 'hrs-2-6', chord: 'C', time: 10.0, duration: 1.5 },
          { id: 'hrs-2-7', chord: 'E', time: 12.0, duration: 1.5 },
          { id: 'hrs-2-8', chord: 'E7', time: 14.0, duration: 1.5 },
          { id: 'hrs-2-9', chord: 'Am', time: 16.0, duration: 1.5 },
          { id: 'hrs-2-10', chord: 'C', time: 18.0, duration: 1.5 },
          { id: 'hrs-2-11', chord: 'D', time: 20.0, duration: 1.5 },
          { id: 'hrs-2-12', chord: 'F', time: 22.0, duration: 1.5 },
          { id: 'hrs-2-13', chord: 'Am', time: 24.0, duration: 1.5 },
          { id: 'hrs-2-14', chord: 'E', time: 26.0, duration: 1.5 },
          { id: 'hrs-2-15', chord: 'Am', time: 28.0, duration: 1.5 },
        ],
      },
    ],
  },

  // 8. Oh Susanna - Stephen Foster (1848)
  {
    id: 'oh-susanna',
    title: 'Oh Susanna',
    artist: 'Stephen Foster',
    difficulty: 1,
    bpm: 120,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Classic American folk song',
        chart: [
          { id: 'os-1-1', chord: 'C', time: 0.0, duration: 2.0 },
          { id: 'os-1-2', chord: 'G', time: 2.5, duration: 2.0 },
          { id: 'os-1-3', chord: 'C', time: 5.0, duration: 2.0 },
          { id: 'os-1-4', chord: 'G', time: 7.5, duration: 2.0 },
          { id: 'os-1-5', chord: 'C', time: 10.0, duration: 2.0 },
          { id: 'os-1-6', chord: 'F', time: 12.5, duration: 2.0 },
          { id: 'os-1-7', chord: 'C', time: 15.0, duration: 2.0 },
          { id: 'os-1-8', chord: 'G', time: 17.5, duration: 2.0 },
          { id: 'os-1-9', chord: 'C', time: 20.0, duration: 2.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Banjo Roll',
        description: 'Upbeat tempo with quick changes',
        chart: [
          { id: 'os-2-1', chord: 'C', time: 0.0, duration: 1.0 },
          { id: 'os-2-2', chord: 'C', time: 1.2, duration: 1.0 },
          { id: 'os-2-3', chord: 'G', time: 2.4, duration: 1.0 },
          { id: 'os-2-4', chord: 'G7', time: 3.6, duration: 1.0 },
          { id: 'os-2-5', chord: 'C', time: 4.8, duration: 1.0 },
          { id: 'os-2-6', chord: 'C', time: 6.0, duration: 1.0 },
          { id: 'os-2-7', chord: 'G', time: 7.2, duration: 1.0 },
          { id: 'os-2-8', chord: 'C', time: 8.4, duration: 1.0 },
          { id: 'os-2-9', chord: 'F', time: 9.6, duration: 1.0 },
          { id: 'os-2-10', chord: 'C', time: 10.8, duration: 1.0 },
          { id: 'os-2-11', chord: 'G', time: 12.0, duration: 1.0 },
          { id: 'os-2-12', chord: 'C', time: 13.2, duration: 1.0 },
        ],
      },
    ],
  },

  // 9. Down By The Riverside - Traditional spiritual
  {
    id: 'down-by-riverside',
    title: 'Down By The Riverside',
    artist: 'Traditional',
    difficulty: 2,
    bpm: 105,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Peaceful spiritual with easy changes',
        chart: [
          { id: 'dbr-1-1', chord: 'G', time: 0.0, duration: 2.5 },
          { id: 'dbr-1-2', chord: 'G', time: 3.0, duration: 2.5 },
          { id: 'dbr-1-3', chord: 'D', time: 6.0, duration: 2.5 },
          { id: 'dbr-1-4', chord: 'G', time: 9.0, duration: 2.5 },
          { id: 'dbr-1-5', chord: 'C', time: 12.0, duration: 2.5 },
          { id: 'dbr-1-6', chord: 'G', time: 15.0, duration: 2.5 },
          { id: 'dbr-1-7', chord: 'D', time: 18.0, duration: 2.5 },
          { id: 'dbr-1-8', chord: 'G', time: 21.0, duration: 2.5 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Gospel Style',
        description: 'Full gospel arrangement',
        chart: [
          { id: 'dbr-2-1', chord: 'G', time: 0.0, duration: 1.5 },
          { id: 'dbr-2-2', chord: 'G', time: 2.0, duration: 1.5 },
          { id: 'dbr-2-3', chord: 'D7', time: 4.0, duration: 1.5 },
          { id: 'dbr-2-4', chord: 'G', time: 6.0, duration: 1.5 },
          { id: 'dbr-2-5', chord: 'G7', time: 8.0, duration: 1.5 },
          { id: 'dbr-2-6', chord: 'C', time: 10.0, duration: 1.5 },
          { id: 'dbr-2-7', chord: 'G', time: 12.0, duration: 1.5 },
          { id: 'dbr-2-8', chord: 'D', time: 14.0, duration: 1.5 },
          { id: 'dbr-2-9', chord: 'G', time: 16.0, duration: 1.5 },
          { id: 'dbr-2-10', chord: 'Em', time: 18.0, duration: 1.5 },
          { id: 'dbr-2-11', chord: 'D', time: 20.0, duration: 1.5 },
          { id: 'dbr-2-12', chord: 'G', time: 22.0, duration: 1.5 },
        ],
      },
    ],
  },

  // 10. Swing Low Sweet Chariot - Traditional spiritual
  {
    id: 'swing-low',
    title: 'Swing Low Sweet Chariot',
    artist: 'Traditional',
    difficulty: 1,
    bpm: 75,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Gentle spiritual with slow tempo',
        chart: [
          { id: 'sl-1-1', chord: 'D', time: 0.0, duration: 3.0 },
          { id: 'sl-1-2', chord: 'G', time: 3.5, duration: 3.0 },
          { id: 'sl-1-3', chord: 'D', time: 7.0, duration: 3.0 },
          { id: 'sl-1-4', chord: 'A', time: 10.5, duration: 3.0 },
          { id: 'sl-1-5', chord: 'D', time: 14.0, duration: 3.0 },
          { id: 'sl-1-6', chord: 'G', time: 17.5, duration: 3.0 },
          { id: 'sl-1-7', chord: 'D', time: 21.0, duration: 3.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Chorus',
        description: 'Complete chorus with harmonies',
        chart: [
          { id: 'sl-2-1', chord: 'D', time: 0.0, duration: 2.0 },
          { id: 'sl-2-2', chord: 'G', time: 2.5, duration: 2.0 },
          { id: 'sl-2-3', chord: 'D', time: 5.0, duration: 2.0 },
          { id: 'sl-2-4', chord: 'A7', time: 7.5, duration: 2.0 },
          { id: 'sl-2-5', chord: 'D', time: 10.0, duration: 2.0 },
          { id: 'sl-2-6', chord: 'D7', time: 12.5, duration: 2.0 },
          { id: 'sl-2-7', chord: 'G', time: 15.0, duration: 2.0 },
          { id: 'sl-2-8', chord: 'D', time: 17.5, duration: 2.0 },
          { id: 'sl-2-9', chord: 'A', time: 20.0, duration: 2.0 },
          { id: 'sl-2-10', chord: 'D', time: 22.5, duration: 2.0 },
        ],
      },
    ],
  },

  // 11. This Land Is Your Land - Woody Guthrie (public domain)
  {
    id: 'this-land',
    title: 'This Land Is Your Land',
    artist: 'Woody Guthrie',
    difficulty: 2,
    bpm: 100,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'American classic with simple chords',
        chart: [
          { id: 'tl-1-1', chord: 'G', time: 0.0, duration: 2.0 },
          { id: 'tl-1-2', chord: 'D', time: 2.5, duration: 2.0 },
          { id: 'tl-1-3', chord: 'G', time: 5.0, duration: 2.0 },
          { id: 'tl-1-4', chord: 'C', time: 7.5, duration: 2.0 },
          { id: 'tl-1-5', chord: 'G', time: 10.0, duration: 2.0 },
          { id: 'tl-1-6', chord: 'D', time: 12.5, duration: 2.0 },
          { id: 'tl-1-7', chord: 'G', time: 15.0, duration: 2.0 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Song',
        description: 'Complete verse and chorus',
        chart: [
          { id: 'tl-2-1', chord: 'G', time: 0.0, duration: 1.5 },
          { id: 'tl-2-2', chord: 'G', time: 2.0, duration: 1.5 },
          { id: 'tl-2-3', chord: 'D', time: 4.0, duration: 1.5 },
          { id: 'tl-2-4', chord: 'D', time: 6.0, duration: 1.5 },
          { id: 'tl-2-5', chord: 'G', time: 8.0, duration: 1.5 },
          { id: 'tl-2-6', chord: 'G7', time: 10.0, duration: 1.5 },
          { id: 'tl-2-7', chord: 'C', time: 12.0, duration: 1.5 },
          { id: 'tl-2-8', chord: 'C', time: 14.0, duration: 1.5 },
          { id: 'tl-2-9', chord: 'G', time: 16.0, duration: 1.5 },
          { id: 'tl-2-10', chord: 'D', time: 18.0, duration: 1.5 },
          { id: 'tl-2-11', chord: 'G', time: 20.0, duration: 1.5 },
        ],
      },
    ],
  },

  // 12. Home On The Range - Traditional American cowboy song
  {
    id: 'home-on-range',
    title: 'Home On The Range',
    artist: 'Traditional',
    difficulty: 2,
    bpm: 85,
    levels: [
      {
        levelNumber: 1,
        name: 'Beginner',
        description: 'Classic cowboy ballad',
        chart: [
          { id: 'hor-1-1', chord: 'G', time: 0.0, duration: 2.5 },
          { id: 'hor-1-2', chord: 'C', time: 3.0, duration: 2.5 },
          { id: 'hor-1-3', chord: 'G', time: 6.0, duration: 2.5 },
          { id: 'hor-1-4', chord: 'D', time: 9.0, duration: 2.5 },
          { id: 'hor-1-5', chord: 'G', time: 12.0, duration: 2.5 },
          { id: 'hor-1-6', chord: 'C', time: 15.0, duration: 2.5 },
          { id: 'hor-1-7', chord: 'G', time: 18.0, duration: 2.5 },
          { id: 'hor-1-8', chord: 'D', time: 21.0, duration: 2.5 },
          { id: 'hor-1-9', chord: 'G', time: 24.0, duration: 2.5 },
        ],
      },
      {
        levelNumber: 2,
        name: 'Full Range',
        description: 'Complete verse with harmonies',
        chart: [
          { id: 'hor-2-1', chord: 'G', time: 0.0, duration: 1.5 },
          { id: 'hor-2-2', chord: 'G7', time: 2.0, duration: 1.5 },
          { id: 'hor-2-3', chord: 'C', time: 4.0, duration: 1.5 },
          { id: 'hor-2-4', chord: 'Cm', time: 6.0, duration: 1.5 },
          { id: 'hor-2-5', chord: 'G', time: 8.0, duration: 1.5 },
          { id: 'hor-2-6', chord: 'A7', time: 10.0, duration: 1.5 },
          { id: 'hor-2-7', chord: 'D', time: 12.0, duration: 1.5 },
          { id: 'hor-2-8', chord: 'D7', time: 14.0, duration: 1.5 },
          { id: 'hor-2-9', chord: 'G', time: 16.0, duration: 1.5 },
          { id: 'hor-2-10', chord: 'G7', time: 18.0, duration: 1.5 },
          { id: 'hor-2-11', chord: 'C', time: 20.0, duration: 1.5 },
          { id: 'hor-2-12', chord: 'G', time: 22.0, duration: 1.5 },
          { id: 'hor-2-13', chord: 'D', time: 24.0, duration: 1.5 },
          { id: 'hor-2-14', chord: 'G', time: 26.0, duration: 1.5 },
        ],
      },
    ],
  },
];

// Legacy export for backwards compatibility
export const sampleSongs = songs;
